'âœ¨ feat': 'feat/*'
'ğŸ›  refactor': 'refactor/*'
'ğŸ“ docs': 'docs/*'
'ğŸ‘‘ chore': 'chore/*'
'âœ… test': 'test/*'
'ğŸ¨ style': 'style/*'
'ğŸ› fix': 'fix/*'
'ğŸ¶ ì˜ê¶Œ': '*/yk/*'
'ğŸˆ ì›ì§„': '*/wj/*'
'ğŸ¦¦ ì˜ì§€': '*/yj/*'
